name: deploy-framework-docker

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: docker login
        run: |
          docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} 
      - uses: actions/checkout@v1
      - name: deploy docker
        run: |
          echo $GITHUB_SHA
          git submodule update --init --recursive framework web docker
          ./tars-latest-deploy-framework.sh true
